#!/usr/bin/env php
<?php

require(__DIR__ . '/vendor/autoload.php');

Dotenv::load(__DIR__);
Dotenv::required(['DB_HOST', 'DB_NAME', 'DB_USER', 'DB_PASS', 'YII_ENV', 'YII_DEBUG']);

defined('YII_CLI') or define('YII_CLI', true);
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

$config = require(__DIR__ . '/config/console.php');
$config['components']['db'] = require(__DIR__ . '/config/test_db.php');

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
