version: '3'
services:
    #NGINX
    nginx:
        image: nginx
        container_name: nginx_news
        volumes:
            - ./nginx/local.conf:/etc/nginx/conf.d/default.conf
            - ./../:/var/www/html/NewsHL
        ports:
            - 8090:80
        restart: always
        depends_on:
            - fpm

    #PHP-FPM
    fpm:
        build:
            context: fpm
        container_name: fpm_news
        volumes:
            - ./../:/var/www/html/NewsHL
        depends_on:
            - mysql
            - memcached
        user: 1000:1000

    #MySQL
    mysql:
        image: mysql:5.7
        container_name: mysql_news
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: newsHL
            MYSQL_PASSWORD: newsHL
            MYSQL_DATABASE: newsHL
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - 3307:3306

    #Memcached
    memcached:
        image: memcached:1.6.5-alpine
        container_name: memcached_news
        ports:
            - 11211:11211
        restart: always
